### ISSUE TITLE
能解释一下这段代码的作用吗

### ISSUE THREAD

**Issue by bethinner** [ImmortalZ/RadarScan#2]
try {
            Field field = ViewPager.class.getDeclaredField("mScroller");
            field.setAccessible(true);
            scroller = new FixedSpeedScroller(MainActivity.this, new AccelerateInterpolator());
            field.set(customViewPager, scroller);
            scroller.setmDuration(duration);
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }

**Comment by ImmortalZ** [comment]
设置viewpager切换速度

**Comment by bethinner** [comment]
@ImmortalZ  设置的目的是什么

**Comment by ImmortalZ** [comment]
让切换时看起来更流畅，当然这个不是必须的，也可以注释掉的

**Comment by zt80hou** [comment]
//当手指左滑速度大于2000时viewpager右滑（注意是item+2）
        if (viewPager.getSpeed() < -1800) {
            viewPager.setCurrentItem(mPosition + 2);
            LogUtil.m("位置 " + mPosition);
            viewPager.setSpeed(0);
        } else if (viewPager.getSpeed() > 1800 && mPosition > 0) {
            //当手指右滑速度大于2000时viewpager左滑（注意item-1即可）
            viewPager.setCurrentItem(mPosition -1);
            LogUtil.m("位置 " + mPosition);
            viewPager.setSpeed(0);
        }

请问2000是怎么计算出来的
