### ISSUE TITLE
可否解释一下这段代码？

### ISSUE THREAD

**Issue by naiyizhang** [ImmortalZ/RadarScan#3]
//根据远近距离的不同计算得到的应该占的半径比例 0.312-0.832
            circleView.setProportion((mDatas.get(i).getDistance() / max + 0.6f) \* 0.52f);

0.6和0.52这两个参数是怎么确定的?最外层的大圆圈是比半径稍微小一点，可是这两个参数这样设置让人困惑

**Comment by ImmortalZ** [comment]
setProportion就是为了计算扫描出来的头像圆显示的位置范围，至于0.6和0.52的取值，我只是测试过几次后发现取这两个值可以让半径范围在0.312-0.832，这样显示得更优雅好看些。

**Comment by naiyizhang** [comment]
got it!明白了，通过算法让半径范围保持在0.3--0.8之内效果应该都不错！感谢耐心解答，Thanks！
